CREATE DATABASE LOJA_INSTRUMENTOS_OLTP
GO

USE LOJA_INSTRUMENTOS_OLTP
GO

CREATE TABLE PRODUTOS(
	IDPRODUTO INT IDENTITY,
	PRODUTO VARCHAR(70) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	CUSTO_MEDIO NUMERIC(10,2) NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	ID_MARCA INT NOT NULL,
	ID_FORNECEDOR INT NOT NULL,
	ID_SUBCATEGORIAS INT NOT NULL,
	CONSTRAINT PK_PRODUTO PRIMARY KEY(IDPRODUTO) 
)
GO

CREATE TABLE MARCAS(
	IDMARCA INT IDENTITY,
	MARCA VARCHAR(25) NOT NULL,
	CONSTRAINT PK_MARCA PRIMARY KEY(IDMARCA) 
)
GO

CREATE TABLE CATEGORIAS(
	IDCATEGORIA INT IDENTITY,
	CATEGORIA VARCHAR(25) NOT NULL,
	CONSTRAINT PK_CATEGORIA PRIMARY KEY(IDCATEGORIA)
)
GO

CREATE TABLE SUB_CATEGORIAS(
	IDSUB INT IDENTITY,
	SUB_CATEGORIA VARCHAR(30) NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	CONSTRAINT PK_SUBCTG PRIMARY KEY(IDSUB) 
)
GO

CREATE TABLE FORNECEDORES(
	IDFORNECEDOR INT IDENTITY,
	FORNECEDOR VARCHAR(25) NOT NULL,
	CONSTRAINT PK_FORNECEDOR PRIMARY KEY(IDFORNECEDOR)
)
GO

CREATE TABLE CLIENTES(
	IDCLIENTE INT IDENTITY,
	NOME VARCHAR(20) NOT NULL,
	SOBRENOME VARCHAR(35) NOT NULL,
	SEXO CHAR(1) CONSTRAINT CK_SEXO CHECK (SEXO IN ('M', 'F')) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	RUA VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL,
	UF CHAR(2) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(IDCLIENTE)
)
GO

CREATE TABLE FUNCIONARIOS(
	IDFUNCIONARIO INT IDENTITY,
	FUNCIONARIO VARCHAR(45) NOT NULL,
	SEXO CHAR(1) CONSTRAINT CK_SEXO_FUN CHECK (SEXO IN ('M', 'F')) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	RUA VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL,
	UF CHAR(2) NOT NULL,
	CARGO VARCHAR(30) NOT NULL,
	SALARIO NUMERIC(10,2) NOT NULL,
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(IDFUNCIONARIO)
)
GO

CREATE TABLE METODO_PAGAMENTO(
	IDMETODO INT IDENTITY,
	FORMA_DE_PAGAMENTO VARCHAR(35) NOT NULL,
	CONSTRAINT PK_METODO PRIMARY KEY(IDMETODO)
)
GO

CREATE TABLE NOTA_FISCAL(
	IDNOTAFISCAL INT IDENTITY,
	DATA DATE DEFAULT GETDATE() NOT NULL,
	TOTAL DECIMAL(10,2),
	ID_FORMA INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_FUNCIONARIO INT NOT NULL,
	CONSTRAINT PK_NOTA PRIMARY KEY(IDNOTAFISCAL)
)
GO

CREATE TABLE ITEM_NOTA(
	IDITEMNOTA INT IDENTITY,
	QUANTIDADE INT,
	VALOR NUMERIC(10,2),
	ID_PRODUTO INT NOT NULL,
	ID_NOTA_FISCAL INT NOT NULL,
	CONSTRAINT PK_ITEM PRIMARY KEY(IDITEMNOTA)
)
GO



