USE LOJA_INSTRUMENTOS_OLTP
GO

/* ADICIONANDO CATEGORIAS */
INSERT INTO CATEGORIAS VALUES('Acessórios')
INSERT INTO CATEGORIAS VALUES('Igreja')
INSERT INTO CATEGORIAS VALUES('Sopro')
INSERT INTO CATEGORIAS VALUES('Teclas')
INSERT INTO CATEGORIAS VALUES('Cordas')
INSERT INTO CATEGORIAS VALUES('Livros')
INSERT INTO CATEGORIAS VALUES('Outlet')
INSERT INTO CATEGORIAS VALUES('Percussão')
INSERT INTO CATEGORIAS VALUES('Áudio')
GO

SELECT * FROM CATEGORIAS
