USE LOJA_INSTRUMENTOS_OLTP
GO

/* ADICIONANDO FORNECEDORES */
INSERT INTO FORNECEDORES VALUES('Alibaba')
INSERT INTO FORNECEDORES VALUES('Oderço')
INSERT INTO FORNECEDORES VALUES('ZadSom')
INSERT INTO FORNECEDORES VALUES('Guimarães Comercial')
INSERT INTO FORNECEDORES VALUES('Izzo Instrumentos')
INSERT INTO FORNECEDORES VALUES('Hayamax')
INSERT INTO FORNECEDORES VALUES('Musitech')
INSERT INTO FORNECEDORES VALUES('Kyodday Comércio')



