USE LOJA_INSTRUMENTOS_OLTP
GO

/* ADICIONANDO CLIENTES 
FONTE: MINHA CABEÇA */


INSERT INTO CLIENTES VALUES('Leandro','Izzo','M','2001-06-02','Leandroaizzo18@gmail.com','Rua José','Osasco','SP')
INSERT INTO CLIENTES VALUES('Pedro','Gois','M','2001-08-20','Pedrogois@gmail.com','Rua 15 de Outubro','Osasco','SP')
INSERT INTO CLIENTES VALUES('Samuel','Silva','M','2002-03-25','Samuelsilva@gmail.com','Rua Abacateiro','Osasco','SP')
INSERT INTO CLIENTES VALUES('Silvana','Silva','F','1973-06-21','Silvanasilva@gmail.com','Rua 21 de Abril','São Paulo','SP')
INSERT INTO CLIENTES VALUES('Rafael','Santos','M','2003-06-04','Rafaelsantos@gmail.com','Travessa 26 de Outubro','São Paulo','SP')
INSERT INTO CLIENTES VALUES('Pedro','Henrique','M','2003-06-21','Pedrohenrique@gmail.com','Viaduto 31 de Março','São Paulo','SP')
INSERT INTO CLIENTES VALUES('Pedro','Azevedo','M','2003-06-29','Pedriazevedo@gmail.com','Rua Acácia Azul','Osasco','SP')
INSERT INTO CLIENTES VALUES('Isabelle','Souza','F','1980-06-02','Isabellesouza@gmail.com','Rua Abraham Lincoln','Guarulhos','SP')
INSERT INTO CLIENTES VALUES('Beatrice','Pereira','F','1999-05-23','Beatricepereira@gmail.com','Rua Abaré','Guarulhos','SP')
INSERT INTO CLIENTES VALUES('Nicolash','Cavalcanti','M','1998-02-12','Nicolashcaval@gmail.com','Rua Abelardo Luz','Guarulhos','SP')
INSERT INTO CLIENTES VALUES('Lupi','Izzo','M','1999-06-22','Lupiizzo@gmail.com','Rua Acrísio Pacheco','Campinas','SP')
INSERT INTO CLIENTES VALUES('Scooby','Izzo','M','1980-02-02','Scoobyizzo@gmail.com','Rua Achilles Brasil','Campinas','SP')
INSERT INTO CLIENTES VALUES('Joao','Sousa','M','1999-12-11','Joaosousa@gmail.com','Rua Acácia','Campinas','SP')
INSERT INTO CLIENTES VALUES('Joao','Souza','M','1998-02-28','Joaosouza@gmail.com','Rua Ada de Oliveira','Campinas','SP')
INSERT INTO CLIENTES VALUES('Joao','Henrique','M','1997-02-23','JoaohenriqueJoaopedro@gmail.com','Rua Adalberto Maia','Campinas','SP')
INSERT INTO CLIENTES VALUES('Joao','Pedro','M','1993-04-04','Joaopedro@gmail.com','Rua Adalgiza Nery','Campinas','SP')
INSERT INTO CLIENTES VALUES('Leandro','Silva','M','1992-12-12','Leandrosilva@gmail.com','Rua 25 de Dezembro','Mauá','SP')
INSERT INTO CLIENTES VALUES('Leandro','Sousa','M','1992-03-03','Leandrosousa@gmail.com','Rua Abadia','Mogi das Cruzes','SP')
INSERT INTO CLIENTES VALUES('Leandro','Henrique','M','1999-03-05','Leandrohenrique@gmail.com','Avenida Afrânio Peixoto','Diadema','SP')
INSERT INTO CLIENTES VALUES('Leandro','Pedro','M','1999-06-02','Leandropedro@gmail.com','Rua Abrão Vicente','Jundiaí','SP')
INSERT INTO CLIENTES VALUES('Beatriz','Alvez','F','1994-10-03','Beaalvez@gmail.com','Rua Abacateiro','Porto Velho','RO')
INSERT INTO CLIENTES VALUES('Carol','Alvez','F','1956-12-03','Carolalvez@gmail.com','Rua Abacateiro','Porto Velho','RO')
INSERT INTO CLIENTES VALUES('Sabrina','Sudan','F','1983-01-16','Sabrinasudan@gmail.com','Rua Abel de Souza','Porto Velho','RO')
INSERT INTO CLIENTES VALUES('Sabrina','Azevedo','F','1972-06-14','Sabrinaazevedo@gmail.com','Rua 13 de Fevereiro','Vale do Paraiso','RO')
INSERT INTO CLIENTES VALUES('Thaiz','Sudan','F','1984-10-03','Thaizsudan@gmail.com','Rua 1º de Maio','Vale do Paraiso','RO')
INSERT INTO CLIENTES VALUES('Thalia','Victoria','F','1966-12-03','Thaliavic@gmail.com','Rua Bahia 20','São Pedro','MS')
INSERT INTO CLIENTES VALUES('Leticia','Victoria','F','1963-01-16','Leticiavic@gmail.com','Rua Adutora','Ribas Do Rio Pardo','MS')
INSERT INTO CLIENTES VALUES('Toddy','Victoria','M','1992-06-14','Toddyvic@gmail.com','Av Alentino Souza Oliveira','Ribas Do Rio Pardo','MS')
INSERT INTO CLIENTES VALUES('Marlene','Victoria','F','1989-10-20','Marlenevic@gmail.com','Vila Aldeia Sassoro','Tacuru','MS')
INSERT INTO CLIENTES VALUES('Samuel','Azevedo','M','1983-01-22','Samuelazev@gmail.com','Travessa Anápolis','Tacuru','MS')
INSERT INTO CLIENTES VALUES('Samuel','Joao','M','1969-07-31','Samueljoa@gmail.com','Rua A Dois','Porto Alegre','RS')
INSERT INTO CLIENTES VALUES('Ernani','Joao','M','1986-08-11','Ernanijoao@gmail.com','Travessa A L','Porto Alegre','RS')
INSERT INTO CLIENTES VALUES('Ernani','Azevedo','M','1978-05-06','Ernaniazev@gmail.com','Rua Adil de Lima','Esmeralda','RS')
INSERT INTO CLIENTES VALUES('Rute','Silva','F','1994-03-22','Rutesilva@gmail.com','Rua 8 de Abril','Esmeralda','RS')
INSERT INTO CLIENTES VALUES('Rute','Joao','F','1965-01-05','Rutejoao@gmail.com','Rua 7 Setembro','Ipê','RS')
INSERT INTO CLIENTES VALUES('Arthur','Rei','M','1976-02-05','Arthurrei@gmail.com','Rua Rafael F. Monteiro','Baltazar','RJ')
INSERT INTO CLIENTES VALUES('Sung','Jin','M','1970-09-05','Sungjin@gmail.com','Rua Laércio Fonseca','Boa Sorte','RJ')
INSERT INTO CLIENTES VALUES('Sung','Woo','M','1975-06-25','Sungjinwo@gmail.com','Avenida Senador Tinoco','Boa Ventura','RJ')
INSERT INTO CLIENTES VALUES('Naruto','Izzo','M','1989-07-11','Narutoizzo@gmail.com','Rua Francisco Diniz','Rosal','RJ')
INSERT INTO CLIENTES VALUES('Goku','Silva','M','1982-09-12','Gokusilva@gmail.com','Rua 22 Ac Mantiqueira','Paty do Alferes','RJ')
INSERT INTO CLIENTES VALUES('Gohan','Izzo','M','1983-09-25','Gohanizzo@gmail.com','Rua Alto Seco','Paty do Alferes','RJ')
INSERT INTO CLIENTES VALUES('Tity','Silva','F','1985-09-05','Titysilva@gmail.com','Estrada Cacarias','Monumento','RJ')
INSERT INTO CLIENTES VALUES('Jenifer','Henrique','F','1987-09-15','Jeniferhenri@gmail.com','Morro do Côco','Rua Areia Branca','RJ')
INSERT INTO CLIENTES VALUES('Jeferson','Henrique','M','1988-09-02','Jefersonhenr@gmail.com','Rua 13 de Maio','Alegre','ES')
INSERT INTO CLIENTES VALUES('Lary','Gonçalves','F','1989-09-21','Larygon@gmail.com','Rua 3 Deolinda Clem','Alto Rio Novo','ES')
INSERT INTO CLIENTES VALUES('Laryssa','Mona','F','1990-12-05','Laryssamon@gmail.com','Rua Anchieta','Vinhatico','ES')
INSERT INTO CLIENTES VALUES('Larissa','Mony','F','1991-11-03','Larimony@gmail.com','Rua Paulo VI','Vinhatico','ES')
INSERT INTO CLIENTES VALUES('Carlos','Lima','M','1993-10-05','Carloslim@gmail.com','Rua José S','Vila Verde','ES')
INSERT INTO CLIENTES VALUES('Alex','Rocha','M','1992-09-06','Alexroc@gmail.com','Rua Afonso Cabral','Passa Quatro','MG')
INSERT INTO CLIENTES VALUES('Rodrigo','Ferreira','M','1993-07-07','Rodrigofer@gmail.com','Rua 21 de Abril','Passa Quatro','MG')
INSERT INTO CLIENTES VALUES('Marli','Fernando','F','1994-08-08','Marlifern@gmail.com','Rua Alfredo Westin','Serrania','MG')
INSERT INTO CLIENTES VALUES('Enzo','Pinto','M','1999-04-11','Enzopin@gmail.com','Rua Capitão Inácio 100','Passagem de Mariana','MG')
INSERT INTO CLIENTES VALUES('Ana','Dora','F','2001-06-05','Anado@gmail.com','Córrego Barreirinha','Sapucaia','MG')
INSERT INTO CLIENTES VALUES('Anna','Lupi','F','2000-09-26','Annalu@gmail.com','Rua 1 de Janeiro','Sapucai-mirim','MG')
INSERT INTO CLIENTES VALUES('Fernanda','Santos','F','2000-04-24','Fernansanto@gmail.com','Praça Castro Alves','Salvador','BA')
INSERT INTO CLIENTES VALUES('Fernando','Ferreira','M','1989-02-05','Fernandofer@gmail.com','Avenida Florinda','Salvador','BA')
INSERT INTO CLIENTES VALUES('Jubiscleide','Costa','M','1992-03-12','Jubiscosta@gmail.com','Rua Antônio Alves','Apora','BA')
INSERT INTO CLIENTES VALUES('Viviane','Silva','F','2001-09-05','Vivianesil@gmail.com','Rua 2 de Julho','Apora','BA')
INSERT INTO CLIENTES VALUES('Danilo','Ferreira','M','1995-10-23','Daniferrei@gmail.com','Rua Assunção','Boquira','BA')
INSERT INTO CLIENTES VALUES('Daniel','Henrique','M','1980-11-05','Danielhenri@gmail.com','Rua Acesso 30','Boquira','BA')
INSERT INTO CLIENTES VALUES('Henrique','Daniel','M','1999-12-05','HenriqDan@gmail.com','Rua Bie Diolino','Apuarema','BA')
INSERT INTO CLIENTES VALUES('Pricila','Barbosa','F','2001-09-12','Pricilabar@gmail.com','Rua Aurélio Rocha','Botupora','BA')
INSERT INTO CLIENTES VALUES('Peterson','Barros','M','2002-05-13','Perterbar@gmail.com','Rua Amargosa','Botupora','BA')
INSERT INTO CLIENTES VALUES('Thalita','Lupi','F','1989-02-08','Thalitalu@gmail.com','Rua Garças','Bauxi','MT')
INSERT INTO CLIENTES VALUES('Thalia','Dora','F','1992-03-10','Thaliadora@gmail.com','Rua Juruti','Bauxi','MT')
INSERT INTO CLIENTES VALUES('Pricila','Barros','F','1988-09-22','Pricilabarros@gmail.com','Rua 21 de Abril','Nova Maringa','MT')
INSERT INTO CLIENTES VALUES('Peterson','Barbosa','M','1987-10-23','Perterbarbosa@gmail.com','Rua Antônio Caetano','Cuiabá','MT')
INSERT INTO CLIENTES VALUES('Ernani','Rocha','M','1998-12-04','Ernaniroch@gmail.com','Rua Bauru','Cuiabá','MT')
INSERT INTO CLIENTES VALUES('Leandro','Barbosa','M','1999-10-03','Lebarbosa@gmail.com','Rua Dom Pedro I','Cuiabá','MT')
INSERT INTO CLIENTES VALUES('Jubiscleuda','Costa','F','2001-04-23','Jubiscleudacosta@gmail.com','Rua 00','Brasília','DF')
INSERT INTO CLIENTES VALUES('Samuel','Araujo','M','1976-02-21','Samuelarau@gmail.com','Rua 1 de Junho','Brasília','DF')
INSERT INTO CLIENTES VALUES('Arthur','Dias','M','1999-03-03','Arthurdias@gmail.com','Quadra SGON Quadra 4','Brasília','DF')
INSERT INTO CLIENTES VALUES('Arthur','Rocha','M','1999-02-20','Arthurrocha@gmail.com','Quadra SQN 306 Bloco A','Brasília','DF')
INSERT INTO CLIENTES VALUES('Fred','Cavalcanti','M','1986-11-10','FredCaval@gmail.com','Quadra SQS 405 Bloco A','Brasília','DF')
INSERT INTO CLIENTES VALUES('Fred','Martins','M','1983-10-11','Fredmar@gmail.com','Quadra SHIGS 704 Bloco J','Brasília','DF')
INSERT INTO CLIENTES VALUES('Joana','Sousa','F','1972-02-23','Joanasou@gmail.com','Rua Floripa','Viamão','RS')
INSERT INTO CLIENTES VALUES('Everson','Pedro','M','1997-10-16','Everpedro@gmail.com','Avenida 3 Jacob Wagner','Nova Boa Vista','RS')
INSERT INTO CLIENTES VALUES('Leandro','Luz','M','1982-12-15','Leluz@gmail.com','Linha Arroio Alegre','Santa Clara Do Sul','RS')
INSERT INTO CLIENTES VALUES('Ewerton','Sousa','M','1973-07-25','Ewertsouza@gmail.com','Rua Araci Boff','Gloria','RS')
INSERT INTO CLIENTES VALUES('Joana','Escobar','F','1990-02-03','Joanaescobar@gmail.com','Rua Alcides Dewes','Gloria','RS')
INSERT INTO CLIENTES VALUES('Pedro','Everson','M','1997-10-16','Peeverson@gmail.com','Rua Pinheiro 670','São Pedro','RS')
INSERT INTO CLIENTES VALUES('Jerferson','Rocha','M','1982-12-15','Jeferrocha@gmail.com','Rua Dez de Abril','Sao Jose Do Herval','RS')
INSERT INTO CLIENTES VALUES('Ewerton','Adrian','M','1999-08-10','Eweradrian@gmail.com','Rua Adolpho Hermes','Salvador Do Sul','RS')
INSERT INTO CLIENTES VALUES('Thalita','Silva','F','1989-02-02','Thalitasil@gmail.com','Rua Albino Neis','Salvador Do Sul','RS')
GO



