USE LOJA_INSTRUMENTOS_OLTP
GO
/* ADICIONANDO SUBCATEGORIAS */
-- Audio = 9
INSERT INTO SUB_CATEGORIAS VALUES('Afinador/Metronomo', 9)
INSERT INTO SUB_CATEGORIAS VALUES('Cabos e Adptadores', 9)
INSERT INTO SUB_CATEGORIAS VALUES('Diapasão', 9)
INSERT INTO SUB_CATEGORIAS VALUES('Fones de Ouvido', 9)
INSERT INTO SUB_CATEGORIAS VALUES('Microfone',9)
GO

-- Percurssão = 8
INSERT INTO SUB_CATEGORIAS VALUES('Pandeiros', 8)
INSERT INTO SUB_CATEGORIAS VALUES('Baqueta', 8)
INSERT INTO SUB_CATEGORIAS VALUES('Baterias', 8)
INSERT INTO SUB_CATEGORIAS VALUES('Tamborim', 8)
GO

-- Outlet = 7
INSERT INTO SUB_CATEGORIAS VALUES('Estojo', 7)
INSERT INTO SUB_CATEGORIAS VALUES('Bíblias', 7)
INSERT INTO SUB_CATEGORIAS VALUES('Métodos Outlet', 7)
INSERT INTO SUB_CATEGORIAS VALUES('Instrumentos de Outlet', 7)
GO

-- Livros = 6
INSERT INTO SUB_CATEGORIAS VALUES('Métodos Cordas', 6)
INSERT INTO SUB_CATEGORIAS VALUES('Métodos Diversos', 6)
INSERT INTO SUB_CATEGORIAS VALUES('Métodos Sopro', 6)
INSERT INTO SUB_CATEGORIAS VALUES('Métodos Teclas', 6)
INSERT INTO SUB_CATEGORIAS VALUES('Teoria Musical', 6)
GO

-- Cordas = 5
INSERT INTO SUB_CATEGORIAS VALUES('Cavaquinhos', 5)
INSERT INTO SUB_CATEGORIAS VALUES('Viola de Arco', 5)
INSERT INTO SUB_CATEGORIAS VALUES('Violão', 5)
INSERT INTO SUB_CATEGORIAS VALUES('Violinos', 5)
INSERT INTO SUB_CATEGORIAS VALUES('Violoncelo', 5)
GO

-- Teclas = 4
INSERT INTO SUB_CATEGORIAS VALUES('Escaleta', 4)
INSERT INTO SUB_CATEGORIAS VALUES('Pianos', 4)
INSERT INTO SUB_CATEGORIAS VALUES('Órgãos', 4)
GO

-- Sopro = 3
INSERT INTO SUB_CATEGORIAS VALUES('Gaita', 3)
INSERT INTO SUB_CATEGORIAS VALUES('Bombardinos', 3)
INSERT INTO SUB_CATEGORIAS VALUES('Clarinetes', 3)
INSERT INTO SUB_CATEGORIAS VALUES('FlugelHorn', 3)
INSERT INTO SUB_CATEGORIAS VALUES('Sax Alto', 3)
INSERT INTO SUB_CATEGORIAS VALUES('Sax Baixo', 3)
INSERT INTO SUB_CATEGORIAS VALUES('Sax Soprano', 3)
INSERT INTO SUB_CATEGORIAS VALUES('Sax Tenor', 3)
INSERT INTO SUB_CATEGORIAS VALUES('Trombones', 3)
INSERT INTO SUB_CATEGORIAS VALUES('Trompetes', 3)
INSERT INTO SUB_CATEGORIAS VALUES('Trompa', 3)
INSERT INTO SUB_CATEGORIAS VALUES('Tubas', 3)
GO

-- Igreja = 2
INSERT INTO SUB_CATEGORIAS VALUES('Acessórios', 2)
INSERT INTO SUB_CATEGORIAS VALUES('Caixa de Coleta', 2)
INSERT INTO SUB_CATEGORIAS VALUES('Estantes Musicais', 2)
INSERT INTO SUB_CATEGORIAS VALUES('Letreiros/Placas', 2)
GO

-- Acessorios = 1
INSERT INTO SUB_CATEGORIAS VALUES('Abraçadeiras', 1)
INSERT INTO SUB_CATEGORIAS VALUES('Arcos', 1)
INSERT INTO SUB_CATEGORIAS VALUES('Bags e Capas', 1)
INSERT INTO SUB_CATEGORIAS VALUES('Breus', 1)
INSERT INTO SUB_CATEGORIAS VALUES('Bocais', 1)
INSERT INTO SUB_CATEGORIAS VALUES('Palhetas', 1)
INSERT INTO SUB_CATEGORIAS VALUES('Prendedor de Partitura', 1)
INSERT INTO SUB_CATEGORIAS VALUES('Surdinas', 1)
INSERT INTO SUB_CATEGORIAS VALUES('Lubrificantes', 1)
INSERT INTO SUB_CATEGORIAS VALUES('Suporte para Instrumentos', 1)
INSERT INTO SUB_CATEGORIAS VALUES('Queixeira', 1)
GO

select * from SUB_CATEGORIAS