USE LOJA_INSTRUMENTOS_OLTP
GO

/* ADICIONANDO METODOS DE PAGAMENTOS*/
INSERT INTO METODO_PAGAMENTO VALUES('Tranferência - Vista')
INSERT INTO METODO_PAGAMENTO VALUES('Depósito - Vista')
INSERT INTO METODO_PAGAMENTO VALUES('Boleto - Vista')
INSERT INTO METODO_PAGAMENTO VALUES('PicPay - Vista')
INSERT INTO METODO_PAGAMENTO VALUES('Mercado Pago - Vista')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Master 2 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Master 3 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Master 4 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Master 5 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Master 10 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Visa - Vencimento')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Visa 2 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Visa 3 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Visa 4 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Visa 5 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Visa 10 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão American 5 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão American 10 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão American 12 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Visa 2 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Visa 3 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Cartão Visa 4 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Pay Pall - 5 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Pay Pall - 12 vezes')
INSERT INTO METODO_PAGAMENTO VALUES('Pag Seguro Web - Vista')
INSERT INTO METODO_PAGAMENTO VALUES('Cheque - Vista')
INSERT INTO METODO_PAGAMENTO VALUES('Pic Pay - Vista')
INSERT INTO METODO_PAGAMENTO VALUES('Mercado Pago - Vista')
GO




