USE LOJA_INSTRUMENTOS_OLTP
GO
/* 
ADICIONANDO DADOS NAS NOTAS FISCAIS 
1- CLIENTE ALEATORIO;
2- FUNCIONARIO ALEATORIO;
3- FORMA DE PAGAMENTO/METODO DE PAGAMENTO ALEATORIA
4- ANO/MES/DIA ALEATORIO 
	OBS: RODAREI CADA ANO 5000 VEZES (2019,2020,2021)
*/

DECLARE
		@ID_CLIENTE INT, @ID_FUNCIONARIO INT, @ID_FORMA INT,
		@DATA DATE

BEGIN
		SET @ID_CLIENTE = 
		(SELECT TOP 1 IDCLIENTE FROM CLIENTES ORDER BY NEWID())

		SET @ID_FUNCIONARIO =
		(SELECT TOP 1 IDFUNCIONARIO FROM FUNCIONARIOS ORDER BY NEWID())

		SET @ID_FORMA =
		(SELECT TOP 1 IDMETODO FROM METODO_PAGAMENTO ORDER BY NEWID())

		/* CADA VEZ QUE RODAR O COMANDO, ALTERE O 2019 POR 2020 E DEPOIS PARA 2021 */
		SET @DATA = (SELECT
					CONVERT(DATE, CONVERT(VARCHAR(15),'2019-' +
					CONVERT(VARCHAR(5),(CONVERT(INT,RAND()*12)) + 1) + '-' +
					CONVERT(VARCHAR(5),(CONVERT(INT,RAND()*27)) + 1))))

		INSERT INTO NOTA_FISCAL(ID_CLIENTE,ID_FUNCIONARIO,ID_FORMA, DATA)   
		VALUES				   (@ID_CLIENTE,@ID_FUNCIONARIO,@ID_FORMA,@DATA)		 

END
GO 5000 
--VAI EXECUTAR 5000 VEZES