USE LOJA_INSTRUMENTOS_OLTP
GO

/* ADICIONANDO ITENS/COMPRAS NO ITEM_NOTA */
-- OBS: Execute esse comando de acordo com a nota fiscal
-- SELECT COUNT(*) FROM NOTA_FISCAL

DECLARE
		@ID_PRODUTO INT,
		@ID_NOTA_FISCAL INT,
		@QUANTIDADE INT,
		@VALOR NUMERIC(10,2),
		@VALOR_TOTAL NUMERIC(10,2)

BEGIN
		SET @ID_PRODUTO =
		(SELECT TOP 1 IDPRODUTO FROM PRODUTOS ORDER BY NEWID())

		SET @ID_NOTA_FISCAL =
		(SELECT TOP 1 IDNOTAFISCAL FROM NOTA_FISCAL ORDER BY NEWID())

		SET @QUANTIDADE =
		(SELECT ROUND(RAND() * 1 + 1, 0))

		SET @VALOR = 
		(SELECT VALOR FROM PRODUTOS WHERE IDPRODUTO = @ID_PRODUTO)

		SET @VALOR_TOTAL = @QUANTIDADE * @VALOR

		INSERT INTO ITEM_NOTA(ID_PRODUTO,ID_NOTA_FISCAL,QUANTIDADE,VALOR)
			VALUES			 (@ID_PRODUTO,@ID_NOTA_FISCAL,@QUANTIDADE,@VALOR_TOTAL)
END
GO 15000