USE LOJA_INSTRUMENTOS_OLTP
GO

/* VISUALIZAR AS NOTAS FISCAIS QUE NÃO ESTÃO COM PRODUTOS, 
E NÃO ESTÃO NO ITEM DE NOTA*/
SELECT IDNOTAFISCAL FROM NOTA_FISCAL
WHERE IDNOTAFISCAL NOT IN(SELECT ID_NOTA_FISCAL FROM ITEM_NOTA)
ORDER BY 1
GO

/* ADICIONANDO NOTAS FISCAIS QUE NÃO POSSUEM PRODUTOS/ITENS COM CURSOR 
OBS: NOTAS PREENCHIDAS COM APENAS 1 PRODUTO ALEATORIO*/
DECLARE
		
		C_NOTAFISCAL CURSOR FOR
		SELECT IDNOTAFISCAL FROM NOTA_FISCAL
		WHERE IDNOTAFISCAL NOT IN(SELECT ID_NOTA_FISCAL FROM ITEM_NOTA)

DECLARE
		@IDNOTAFISCAL INT,
		@ID_PRODUTO INT,
		@VALOR DECIMAL(10,2)

OPEN C_NOTAFISCAL

FETCH NEXT FROM C_NOTAFISCAL
INTO @IDNOTAFISCAL

WHILE @@FETCH_STATUS = 0
BEGIN
	SET @ID_PRODUTO =
	(SELECT TOP 1 IDPRODUTO FROM PRODUTOS ORDER BY NEWID())

	SET @VALOR =
	(SELECT VALOR FROM PRODUTOS WHERE IDPRODUTO = @ID_PRODUTO)

	INSERT INTO ITEM_NOTA(ID_PRODUTO, ID_NOTA_FISCAL, QUANTIDADE, VALOR)
	VALUES(@ID_PRODUTO, @IDNOTAFISCAL,1, @VALOR)

FETCH NEXT FROM C_NOTAFISCAL
INTO @IDNOTAFISCAL

END

CLOSE C_NOTAFISCAL
DEALLOCATE C_NOTAFISCAL
GO

