USE LOJA_INSTRUMENTOS_OLTP
GO

--CRIANDO VIEWS
/* RELATORIO DOS ITENS/PRODUTOS, SEU VALOR, 
QUANTIDADE, E QUAL NOTA ELE PERTENCE*/
CREATE VIEW V_ITEM_NOTAS AS
SELECT ID_NOTA_FISCAL AS "NOTA FISCAL",
		PRODUTO,
		P.VALOR,
		QUANTIDADE,
		I.VALOR AS "TOTAL DO ITEM"
FROM PRODUTOS P
INNER JOIN ITEM_NOTA I
ON P.IDPRODUTO = I.ID_PRODUTO
GO

/* RELATORIO COMPLETO DE COMPRA,
QUEM COMPROU, SEXO, HORARIO, A NOTAFISCAL, O PRODUTO E O TOTAL */
CREATE VIEW V_COMPRAS AS
SELECT C.NOME, C.SOBRENOME, C.SEXO, N.DATA, N.IDNOTAFISCAL, P.PRODUTO, N.TOTAL
FROM CLIENTES C
INNER JOIN NOTA_FISCAL N
ON C.IDCLIENTE = N.ID_CLIENTE
INNER JOIN ITEM_NOTA I
ON N.IDNOTAFISCAL = I.ID_NOTA_FISCAL
INNER JOIN PRODUTOS P
ON P.IDPRODUTO = I.ID_PRODUTO

SELECT * FROM V_ITEM_NOTAS
SELECT * FROM V_COMPRAS





