USE LOJA_INSTRUMENTOS_OLTP
GO
/* ATUALIZADOR DE NOTAS FISCAIS */

/* RELATORIO DA SOMA DOS GASTOS POR NOTA FISCAL */
CREATE VIEW V_TOTAL_NOTAFISCAL AS
SELECT ID_NOTA_FISCAL, SUM(VALOR) AS SOMA
FROM ITEM_NOTA
GROUP BY ID_NOTA_FISCAL

/* CARGA NOTA FISCAL (TOTAL) */
--SOMA = TOTAL GASTO NA NOTA
CREATE VIEW V_CARGA_NOTAFISCAL AS
SELECT N.IDNOTAFISCAL, N.TOTAL AS TOTAL_NOTA, T.SOMA
FROM NOTA_FISCAL N
INNER JOIN V_TOTAL_NOTAFISCAL T
ON IDNOTAFISCAL = ID_NOTA_FISCAL
GO

UPDATE V_CARGA_NOTAFISCAL SET TOTAL_NOTA = SOMA
GO

SELECT * FROM V_TOTAL_NOTAFISCAL
SELECT * FROM V_CARGA_NOTAFISCAL