USE LOJA_STAGE
GO

CREATE TABLE ST_CLIENTES(
	IDCLIENTE INT DEFAULT NULL,
	NOME_COMPLETO VARCHAR(80) DEFAULT NULL,
	SEXO VARCHAR(6) DEFAULT NULL,
	NASCIMENTO DATE DEFAULT NULL,
	CIDADE VARCHAR(20) DEFAULT NULL,
	UF VARCHAR(6) DEFAULT NULL,
	EMAIL VARCHAR(100) DEFAULT NULL
)
GO

CREATE TABLE ST_FUNCIONARIOS(
	IDFUNCIONARIO INT DEFAULT NULL,
	FUNCIONARIO VARCHAR(50) DEFAULT NULL,
	SEXO VARCHAR(6) DEFAULT NULL,
	CARGO VARCHAR(40) DEFAULT NULL
)
GO

CREATE TABLE ST_CATEGORIAS(
	IDCATEGORIA INT DEFAULT NULL,
	CATEGORIA VARCHAR(40) DEFAULT NULL,
)
GO

CREATE TABLE ST_SUBCATEGORIAS(
	IDSUB INT DEFAULT NULL,
	SUB_CATEGORIA VARCHAR(35) DEFAULT NULL
)
GO

CREATE TABLE ST_FORNECEDORES(
	IDFORNECEDOR INT DEFAULT NULL,
	FORNECEDOR VARCHAR(30) DEFAULT NULL,
)
GO

CREATE TABLE ST_MARCAS(
	IDMARCA INT DEFAULT NULL,
	MARCA VARCHAR(30) DEFAULT NULL
)
GO

CREATE TABLE ST_PRODUTOS(
	IDPRODUTO INT DEFAULT NULL,
	PRODUTO VARCHAR(100) DEFAULT NULL,
	VALOR_UNIT NUMERIC(10,2) DEFAULT NULL,
	CUSTO_MEDIO NUMERIC(10,2) DEFAULT NULL
)
GO

CREATE TABLE ST_NOTAS(
	IDNOTA INT DEFAULT NULL
)
GO

CREATE TABLE ST_METODOS(
	IDMETODO INT DEFAULT NULL,
	FORMA_PAGAMENTO VARCHAR(45) DEFAULT NULL
)
GO

CREATE TABLE ST_FATO(
	ID_CLIENTE INT DEFAULT NULL,
	ID_FUNCIONARIO INT DEFAULT NULL,
	ID_FORNECEDOR INT DEFAULT NULL,
	ID_PRODUTO INT DEFAULT NULL,
	ID_CATEGORIA INT DEFAULT NULL,
	ID_SUB INT DEFAULT NULL,
	ID_MARCA INT DEFAULT NULL,
	ID_NOTA INT DEFAULT NULL,
	ID_METODO INT DEFAULT NULL,
	DATA DATE DEFAULT NULL,
	QUANTIDADE INT DEFAULT NULL,
	TOTAL_ITEM NUMERIC(10,2) DEFAULT NULL,
	CUSTO_TOTAL NUMERIC(10,2) DEFAULT NULL,
	LUCRO_TOTAL NUMERIC(10,2) DEFAULT NULL
)
GO
