USE LOJA_INSTRUMENTOS_OLTP
GO

CREATE VIEW RELATORIO_VENDAS_FATO AS
SELECT  C.IDCLIENTE,
		F.IDFUNCIONARIO,
		P.IDPRODUTO,
		CT.IDCATEGORIA,
		S.IDSUB,
		MA.IDMARCA,
		FO.IDFORNECEDOR,
		N.IDNOTAFISCAL,
		M.IDMETODO,
		I.QUANTIDADE,
		(I.QUANTIDADE * P.CUSTO_MEDIO) AS CUSTO_TOTAL,
		(I.VALOR - (I.QUANTIDADE * P.CUSTO_MEDIO)) AS LUCRO_TOTAL,
		I.VALOR AS VALOR_VENDA_TOTAL,
		N.DATA AS DATA
FROM NOTA_FISCAL N
INNER JOIN ITEM_NOTA I
ON N.IDNOTAFISCAL = I.ID_NOTA_FISCAL
INNER JOIN CLIENTES C
ON C.IDCLIENTE = N.ID_CLIENTE
INNER JOIN FUNCIONARIOS F
ON F.IDFUNCIONARIO = N.ID_FUNCIONARIO
INNER JOIN PRODUTOS P
ON P.IDPRODUTO = ID_PRODUTO
INNER JOIN METODO_PAGAMENTO M
ON M.IDMETODO = N.ID_FORMA
INNER JOIN FORNECEDORES FO
ON FO.IDFORNECEDOR = P.ID_FORNECEDOR
INNER JOIN CATEGORIAS CT
ON CT.IDCATEGORIA = P.ID_CATEGORIA
INNER JOIN SUB_CATEGORIAS S
ON S.IDSUB = P.ID_SUBCATEGORIAS
INNER JOIN MARCAS MA
ON MA.IDMARCA = P.ID_MARCA
GO 

