/* ADICIONANDO AS FKS NA FATO*/
USE LOJA_DW
GO

ALTER TABLE FATO ADD CONSTRAINT FK_FATO_NOTAS
FOREIGN KEY (ID_NOTA) REFERENCES DIM_NOTAS(IDSK)
GO

ALTER TABLE FATO ADD CONSTRAINT FK_FATO_CLIENTES
FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTES(IDSK)
GO

ALTER TABLE FATO ADD CONSTRAINT FK_FATO_MARCAS
FOREIGN KEY (ID_MARCA) REFERENCES DIM_MARCAS(IDSK)
GO

ALTER TABLE FATO ADD CONSTRAINT FK_FATO_FUNCIONARIOS
FOREIGN KEY (ID_FUNCIONARIO) REFERENCES DIM_FUNCIONARIOS(IDSK)
GO

ALTER TABLE FATO ADD CONSTRAINT FK_FATO_METODO
FOREIGN KEY (ID_METODO) REFERENCES DIM_METODOS(IDSK)
GO

ALTER TABLE FATO ADD CONSTRAINT FK_FATO_PROD
FOREIGN KEY (ID_PRODUTO) REFERENCES DIM_PRODUTOS(IDSK)
GO

ALTER TABLE FATO ADD CONSTRAINT FK_FATO_FORNECEDOR
FOREIGN KEY (ID_FORNECEDOR) REFERENCES DIM_FORNECEDORES(IDSK)
GO

ALTER TABLE FATO ADD CONSTRAINT FK_FATO_CATEGORIAS
FOREIGN KEY (ID_CATEGORIA) REFERENCES DIM_CATEGORIAS(IDSK)
GO

ALTER TABLE FATO ADD CONSTRAINT FK_FATO_SUB
FOREIGN KEY (ID_SUB) REFERENCES DIM_SUBCATEGORIAS(IDSK)
GO

ALTER TABLE FATO ADD CONSTRAINT FK_FATO_TEMPO
FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO(IDSK)
GO