USE LOJA_DW
GO

	-----------------------
	----CRIAÇÃO DA PROC----
	-----------------------

CREATE PROC CARGA_FATODW
AS

	DECLARE @FINAL DATETIME
	DECLARE @INICIAL DATETIME

	SELECT @FINAL = MAX(DATA)
	FROM DIM_TEMPO T

	SELECT @INICIAL = MAX(DATA)
	FROM FATO FT
	JOIN DIM_TEMPO T 
	ON (FT.ID_TEMPO = T.IDSK)

	IF @INICIAL IS NULL
	BEGIN
		SELECT @INICIAL = MIN(DATA)
		FROM DIM_TEMPO T
	END

	INSERT INTO LOJA_DW.DBO.FATO(
		ID_NOTA,
		ID_CLIENTE,
		ID_FUNCIONARIO,
		ID_METODO,
		ID_FORNECEDOR,
		ID_MARCA,
		ID_CATEGORIA,
		ID_SUB,
		ID_PRODUTO,
		ID_TEMPO,
		QUANTIDADE,
		TOTAL_ITEM,
		CUSTO_TOTAL,
		LUCRO_TOTAL
		)
	SELECT
		N.IDSK AS IDNOTA,
		C.IDSK AS IDCLIENTE,
		FU.IDSK AS IDFUNCIONARIO,
		M.IDSK AS IDMETODO,
		FN.IDSK AS IDFORNECEDOR,
		MA.IDMARCA AS IDMARCA,
		CA.IDCATEGORIA AS IDCATEGORIA,
		S.IDSUB AS IDSUB,
		P.IDSK AS IDPRODUTO,
		T.IDSK AS IDTEMPO,
		F.QUANTIDADE,
		F.TOTAL_ITEM,
		F.CUSTO_TOTAL,
		F.LUCRO_TOTAL

	FROM
		LOJA_STAGE.DBO.ST_FATO F

		INNER JOIN DIM_METODOS M
		ON (F.ID_METODO = M.IDMETODO)

		INNER JOIN DIM_NOTAS N
		ON (F.ID_NOTA = N.IDNOTA)

		INNER JOIN DIM_CATEGORIAS CA
		ON (F.ID_CATEGORIA = CA.IDCATEGORIA)

		INNER JOIN DIM_MARCAS MA
		ON (F.ID_MARCA = MA.IDMARCA)

		INNER JOIN DIM_SUBCATEGORIAS S
		ON (F.ID_SUB = S.IDSUB)

		INNER JOIN DIM_FORNECEDORES FN
		ON (F.ID_FORNECEDOR = FN.IDFORNECEDOR
			AND (FN.INICIO <= F.DATA
			AND (FN.FIM >= F.DATA) OR (FN.FIM IS NULL)))

		INNER JOIN DIM_CLIENTES C
		ON (F.ID_CLIENTE = C.IDCLIENTE
			AND (C.INICIO <= F.DATA
			AND (C.FIM >= F.DATA) OR (C.FIM IS NULL)))

		INNER JOIN DIM_FUNCIONARIOS FU
		ON (F.ID_FUNCIONARIO = FU.IDFUNCIONARIO
			AND (FU.INICIO <= F.DATA
			AND (FU.FIM >= F.DATA) OR (FU.FIM IS NULL)))

		INNER JOIN DIM_PRODUTOS P
		ON (F.ID_PRODUTO = P.IDPRODUTO
			AND (P.INICIO <= F.DATA
			AND (P.FIM >= F.DATA) OR (P.FIM IS NULL)))

		INNER JOIN DIM_TEMPO T
		ON (CONVERT(VARCHAR, T.DATA,102) = CONVERT(VARCHAR,
		F.DATA,102))
		WHERE F.DATA > @INICIAL AND F.DATA < @FINAL
