USE LOJA_DW
GO

/* CONFERINDO SE OS DADOS DO OLTP PASSARAM PELO STAGE E FORAM ATÉ O DW */
SELECT * FROM LOJA_INSTRUMENTOS_OLTP.DBO.RELATORIO_VENDAS_FATO -- 20525

SELECT COUNT(*) FROM LOJA_STAGE.DBO.ST_FATO -- 20525

SELECT COUNT(*) FROM LOJA_DW.DBO.FATO -- 20525

SELECT * FROM FATO
ORDER BY 1
GO